### ISSUE TITLE
.NET World Video link problem

### ISSUE THREAD

**Issue by kmgallahan** [thangchung/awesome-dotnet-core#103]
Under the **Videos** section, the [.NET World YouTube link](https://www.youtube.com/channel/UClW5uIyHKPhfSEloQxn7b0Q) leads to a terminated account with the following message:

> This account has been terminated due to multiple or severe violations of YouTube's policy against spam, deceptive practices, and misleading content or other Terms of Service violations. 

There is [a separate Facebook page here](https://www.facebook.com/dotnetworld.org) named "Dot NET World" which could be added to the **Community** section. I'm not sure if they're related, or if anybody might know who used to run the terminated YouTube page...

**Comment by thangchung** [comment]
@kmgallahan Thank you for your report. Could you add a PR for what you mentioned above? I really appreciate about what did you point out.

**Comment by kmgallahan** [comment]
Closing this issue as it has already been 2 months, so I guess the dead link will live on.
