### ISSUE TITLE
ASP.NET MVC, Nancy and other projects

### ISSUE THREAD

**Issue by dustinmoris** [thangchung/awesome-dotnet-core#123]
Some web frameworks are listed under application frameworks. I propose to either move the web frameworks to the web frameworks section or merge these categories, otherwise it is misleading information as someone might look for web frameworks and not find some of the most popular web frameworks.

**Comment by thangchung** [comment]
@dustinmoris Thanks for your suggestion. I will careful have a look at that too see can we merge it or not 👍
