### ISSUE TITLE
A repo to Research "Arch"

### ISSUE THREAD

**Issue by JonathanLoscalzo** [thangchung/awesome-dotnet-core#139]
Could you research some libs/patterns in this repo https://github.com/Arch?

It's a cool repo, with arquitectural patterns and implementations.

**Comment by thangchung** [comment]
Good suggestion, but any idea where can I put it on our list?

**Comment by JonathanLoscalzo** [comment]
I think we would have 2 options:
1)Find one repo at a time, and detect the category where the merge could be made
2) Invite Arch's members from to merge.
3) Add new Category... it could be "Interesting Repo", after https://github.com/thangchung/awesome-dotnet-core#starter-kits, with the link to the repo.

**Comment by thangchung** [comment]
@JonathanLoscalzo Sorry for a long time no actions on this issue. I have reviewed it. It is really good for us. I will add it now. Thank for your contribution 👍
