### ISSUE TITLE
Should NodaTime be under Date andTime

### ISSUE THREAD

**Issue by SanderDeclerck** [thangchung/awesome-dotnet-core#154]
NodaTime is currently under "**Internationalization**", which might be correct as it makes working with date and time over different timezones and calendar systems easier.

However, there is also a category "**Date and Time**", and it seems odd to me to not find NodaTime there.

**Comment by SanderDeclerck** [comment]
So the main question is: where should NodaTime be?

- Internationalization
- Date and Time
- Both

**Comment by thangchung** [comment]
@SanderDeclerck I moved it to **Date and Time**. I will consider seeing if we can remove **Internationalization** section or not. But I will close this issue for now. Thank very much for your suggestion.
