### ISSUE TITLE
Payments SDKs supported by Asp.Net Core (2.x) 

### ISSUE THREAD

**Issue by a-patel** [thangchung/awesome-dotnet-core#165]
Payments SDKs supported by Asp.Net Core (2.x) 

I think only Stripe is available.

**Comment by thangchung** [comment]
@a-patel Is it `Stripe`?

**Comment by a-patel** [comment]
@thangchung 
yes, typo mistake

**Comment by a-patel** [comment]
Does PayPal and any other payment gateway support .Net Core (2.x)?

**Comment by thangchung** [comment]
I am not sure about that. I will investigate around to see what can I find

**Comment by a-patel** [comment]
Any update?

**Comment by thangchung** [comment]
@a-patel Sorry for a long time no updates. 
I have found a couple of days that Paypal has released the package in NuGet for .NET Core 2.x (only in Beta version). You can see at https://github.com/paypal/PayPal-NET-SDK/tree/2.0-beta. And another famous payment gateway like Braintree, you can found at https://github.com/braintree/braintree_dotnet

**Comment by a-patel** [comment]
Thanks @thangchung
