### ISSUE TITLE
Invalid entry emitter

### ISSUE THREAD

**Issue by empitegayan** [thangchung/awesome-dotnet-core#191]
[emitter](https://emitter.io/) - Free open source real-time messaging service that connects all devices. This publish-subscribe messaging API is built for speed and security.

This has no asp.net core support

**Comment by thangchung** [comment]
@empitegayan Hi, I have found that they have the repo for .NET at https://github.com/emitter-io/csharp

**Comment by thangchung** [comment]
Close it due to no answer from the asker.
