### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by RehanSaeed** [thangchung/awesome-dotnet-core#2]
Consider adding Colorful.Console which is adding support in a few days and ASP.Net MVC Boilerplate which is a project template.

**Comment by thangchung** [comment]
@RehanSaeed Thanks for your suggestion. I have added the Colorful.Console at [build automation](https://github.com/thangchung/awesome-dotnet-core#build-automation). The ASP.NET MVC Boilerplate added in the last couples of days. Are you happy to close this issue?

**Comment by RehanSaeed** [comment]
That one has a similar name but is different. https://visualstudiogallery.msdn.microsoft.com/6cf50a48-fc1e-4eaf-9e82-0b2a6705ca7d

**Comment by thangchung** [comment]
@RehanSaeed Sorry, but I have a little bit confuse. Could you check [the application-templates](https://github.com/thangchung/awesome-dotnet-core#application-templates)? There is the **ASP.NET MVC Boilerplate** inside this bookmark. Is it what you are mentioning?

**Comment by RehanSaeed** [comment]
Ah, sorry, I was looking at 'Starter Kits and Sample Projects'.

**Comment by thangchung** [comment]
Okay. So could I close this issue?
