### ISSUE TITLE
Peachpie and a couple of file managers for .NET Core

### ISSUE THREAD

**Issue by gordon-matt** [thangchung/awesome-dotnet-core#237]
Nice list. Another project you can add is "Peachpie", which is a PHP compiler for .NET Core. It's working very well now - they even have WordPress running on it. Project here: https://github.com/peachpiecompiler/peachpie and their website is here: https://www.peachpie.io/

Also, I'd like to add 2 file managers (both are my projects):

- [elFinder.NetCore](https://github.com/gordon-matt/elFinder.NetCore)
 This is a connector for .NET Core (and a demo project)
- [peachpie-responsive-file-manager](https://github.com/gordon-matt/peachpie-responsive-file-manager)
 As the name implies, this is a PHP file manager that runs on Peachpie

**Comment by gordon-matt** [comment]
ko co gi  ;-)   I hope it's useful for you and others

**Comment by thangchung** [comment]
@gordon-matt How do you know the Vietnamese language? Does it come from Google Translate? :D

**Comment by gordon-matt** [comment]
@thangchung No, I lived and worked in Ha Noi for 6 years.

**Comment by thangchung** [comment]
Really. So where do you live now?

**Comment by gordon-matt** [comment]
Toi song o nuoc Uc.  :-D   Anyway, if you have any questions about the file managers, just feel free to ask.

**Comment by thangchung** [comment]
Thank you very much 👍
