### ISSUE TITLE
Glimpse - no stable .net core support

### ISSUE THREAD

**Issue by wernerbarnard** [thangchung/awesome-dotnet-core#244]
Hi,

Am I missing something, or does the referenced http://getglimpse.com under Profiling not support .net core?  Seems the beta of Glimpse.Prototype works "sort of" - but in the main Glimpse repo I can only see .net Framework support.

**Comment by thangchung** [comment]
@wernerbarnard Thank you for your finding and recommend. I just updated Glimpse to `unstable version` so that end-users shall be very careful when used it.
