### ISSUE TITLE
Add ninjanye.SearchExtensions

### ISSUE THREAD

**Issue by LordMike** [thangchung/awesome-dotnet-core#259]
Not sure where it belongs. It's a package that helps you make search-related queries against data sources... F.ex. on Entity Framework.

* https://github.com/ninjanye/SearchExtensions
* https://ninjanye.github.io/SearchExtensions/simplesearch.html
* https://www.nuget.org/packages/NinjaNye.SearchExtensions/

**Comment by thangchung** [comment]
Hi @LordMike. I think we could put it to **Searching** section.

**Comment by thangchung** [comment]
Move to PR #260
