### ISSUE TITLE
Micro samples for aspnetcore fundamentals

### ISSUE THREAD

**Issue by dodyg** [thangchung/awesome-dotnet-core#26]
https://github.com/dodyg/practical-aspnetcore

I have 26 micro samples of aspnetcore fundamentals so far and it is updated daily.

**Comment by thangchung** [comment]
@dodyg Just have a look your repo. It is actually cool. Could you please make an FR to my repo, please?

**Comment by dodyg** [comment]
FR?

**Comment by thangchung** [comment]
FR = Full Request
You can submit a full request from this repo, then add your repo into this main repo, finally full a request back.
