### ISSUE TITLE
Size of projects

### ISSUE THREAD

**Issue by Jogai** [thangchung/awesome-dotnet-core#282]
Sometimes I see a remark about the size of a project. I dont think that should matter much. The same discussion is held over here https://github.com/quozd/awesome-dotnet/pull/589#issuecomment-347550197

Key points from there:

- Not spending time on a small thing is still time saved
- Size is relative to the overall size of the project.
- A tested library is always better than something untested that's quickly put together.

**Comment by thangchung** [comment]
Agreed with @Jogai. I have added the label `Project is possibly too small`, and will have a look to create more labels to increase more meaningful then.
