### ISSUE TITLE
Starz, watch and github forks

### ISSUE THREAD

**Issue by Diaskhan** [thangchung/awesome-dotnet-core#335]
Maybe, we should add a starz to repos, 

after project link count of stars in github ? 
Maybe need some program that scans all links and update the stars count !

**Comment by Diaskhan** [comment]
Maybe add second page, that starz source page and added in repositroy ?
I could write it. its very simple !

**Comment by Diaskhan** [comment]
By count of statz and forks we could make objective analyz that repository will supported in future! And on what stage is library! Alpha,stable and how many users is use it !  For example this is veujs ui framework that has https://github.com/ElemeFE/element

27 k stars! I think is repo has LTS!

**Comment by ngohungphuc** [comment]
If you can do that please submit PR and I will review it.
Thank you

**Comment by Diaskhan** [comment]
If U call 
https://api.github.com/repos/jasonrudolph/keyboard

Then api returns !

![image](https://user-images.githubusercontent.com/15046677/43401861-0746d152-9433-11e8-904d-76ea62ed0013.png)

**Comment by Diaskhan** [comment]
And this would help
https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/console-webapiclient

**Comment by LordMike** [comment]
What do others do here.. Let their CI system commit back to the repository? 

There's no point in maintaining this by running a tool manually.

**Comment by mzorec** [comment]
I disagree by adding stars to the repository. This might give unfair disadvantage to the newer repositories which might be better than the old one but user will not check them because old repository have more stars. Also user will make in this case wrong choice which lib to use.

**Comment by Diaskhan** [comment]
There Have another Good vision. Is the date of last Commit! For example it could be september of 2013 or january of 2018.

Look at https://github.com/icsharpcode/AvalonEdit
The AvalonEdit project is dead !

**Comment by LordMike** [comment]
Be aware that once a project is feature complete, there is rarely a reason to change it. If dependencies don't change and other circumstances stay the same -- the project will "seem" dead even though it isn't.

An example would be any form of maths / calculations / algorithms library. Once they're done .. they're done.

**Comment by Diaskhan** [comment]
It is possible to include automatic script that will gather links and update file on github ?

**Comment by thangchung** [comment]
@Diaskhan @ngohungphuc @LordMike I thought about it last year, and look around some of the other awesome projects, but actually, they added start and forks manually. I think that does not make sense to do that way. If there is anything way to do that with CI then it would be great.

**Comment by Diaskhan** [comment]
@thangchung  github  CI is not for free! Possible must payed for CI!

**Comment by Diaskhan** [comment]
Actually i could write tool to parse and make starz? @thangchung in future u could by yourself code in c#?

**Comment by Diaskhan** [comment]
This is example  for travic ci and C#
https://github.com/nbarbettini/csharp-travis-example

**Comment by thangchung** [comment]
@Diaskhan Yes, agreed that we can code for this type of functionality, but then we need to let the CI commit changes to GitHub again. It might make more cumbersome for `awesome-dotnetcode` project back then.

**Comment by Diaskhan** [comment]
https://stackoverflow.com/questions/28749727/xunit-add-info-to-output
Output of xunit!

**Comment by Diaskhan** [comment]
Commit data to travis https://www.vinaygopinath.me/blog/tech/commit-to-master-branch-on-github-using-travis-ci/

**Comment by Diaskhan** [comment]
We dont gonna be touch main source file !
We gonna create new file with stars and last cimmit information !

**Comment by thangchung** [comment]
Close it now. Because we don't work on it.
