### ISSUE TITLE
Need Extension or Library section

### ISSUE THREAD

**Issue by ngohungphuc** [thangchung/awesome-dotnet-core#343]
Currently I have encounter some project can either put into application framework or application templates and is just lib or some extension so I think we can create Extension or Library section for these kind of project

**Comment by thangchung** [comment]
That would be great with that way, but the thing is there is a lot of Extensions project in this list that spread out along the way of this list as well.

**Comment by thangchung** [comment]
@ngohungphuc Is it the same with #376?
