### ISSUE TITLE
Remove Scaffolder Library

### ISSUE THREAD

**Issue by abarrak** [thangchung/awesome-dotnet-core#371]
Removing [Scaffolder](https://github.com/thangchung/awesome-dotnet-core#application-templates) from application templates, since it has no documentation or getting started guide, incomplete, and [seems discounted](https://github.com/dncuug/scaffolder/pull/22),

**Comment by ngohungphuc** [comment]
Cc @thangchung

**Comment by ngohungphuc** [comment]
We will get on to that

**Comment by thangchung** [comment]
Yeah. Agreed with you. They have not started anything new during the last 2 years.
