### ISSUE TITLE
Net core expersion or script engines

### ISSUE THREAD

**Issue by Diaskhan** [thangchung/awesome-dotnet-core#376]
Need a experssion engine section 
Roslyn is not cover all use cases! And again its not easy to plugin and work! But need to check net core compatiblity ! 

Roslyn Project - Scripting API - https://github.com/dotnet/roslyn/wiki/Scripting-API-SamplesThis is the new Microsoft Official Compiler as a service library. I suggest to consider using Roslyin instead of DynamicExpresso whenever possible.Mono.CSharp - C# Compiler Service and Runtime Evaulator - http://docs.go-mono.com/index.aspx?link=N%3AMono.CSharpNCalc - Mathematical Expressions Evaluator for .NET - http://ncalc.codeplex.com/David Wynne CSharpEval https://github.com/DavidWynne/CSharpEvalCSharp Eval http://csharp-eval.com/C# Expression Evaluator http://csharpeval.codeplex.com/Jint - Javascript interpreter for .NET - http://jint.codeplex.com/Jurassic - Javascript compiler for .NET - http://jurassic.codeplex.com/Javascrpt.net - javascript V8 engine - http://javascriptdotnet.codeplex.com/CS-Script - http://www.csscript.net/IronJS, IronRuby, IronPythonpaxScript.NET http://eco148-88394.innterhost.net/paxscriptnet/

**Comment by lousaibiao** [comment]
`https://github.com/DavidWynne/CSharpEvalCSharp` ,`http://eco148-88394.innterhost.net/paxscriptnet/ `, `http://csharp-eval.com/C#` are  404 pages.

**Comment by Diaskhan** [comment]
And this is too https://github.com/davideicardi/DynamicExpresso

**Comment by thangchung** [comment]
@Diaskhan So do you happy if I create the `Expression Engine` section, then you add libs for it then?

**Comment by Diaskhan** [comment]
And this link to 
https://github.com/davideicardi/DynamicExpresso

Thats why iam telling need date of last commit and gatheted stars!

**Comment by Diaskhan** [comment]
Thats all!
