### ISSUE TITLE
Commercial products

### ISSUE THREAD

**Issue by SebastianStehle** [thangchung/awesome-dotnet-core#407]
Is the list also open for commercial products? Because workflowengine.net is open source but not free. https://workflowengine.io/pricing/

If the list is open it would be good to have something like a badge or so for commercial products.

**Comment by thangchung** [comment]
@SebastianStehle Thank you for your idea. We start this list as the open source project list so that I don't think we should put the commercial products. We might start another list for these products like that.

@ngohungphuc Give us some idea, please.

**Comment by ngohungphuc** [comment]
Personally I think this project cant be in the list because is commercial product and the dev team dont expose open source repo for user to use or contribute

**Comment by fidergo-stephane-gourichon** [comment]
Hi everyone. Not commenting on this repo's policy or any quality of workflowengine.net which I don't know, just to clarify a point. All emphasis below is mine.

> workflowengine.net is **open source** but not free. https://workflowengine.io/pricing/

It is open source? Let's see [End User License Agreement | Workflow Engine](https://workflowengine.io/agreements/eula/ "End User License Agreement | Workflow Engine")

> **resale or distribution** of all or any portion of **all source code and intellectual property will be prosecuted** to the fullest extent of all applicable local, federal and international laws. All OPTIMAJET libraries, source code, redistributables and other files remain OPTIMAJET’s exclusive property. **You may not distribute any files**, except those that OPTIMAJET has expressly designated as Redistributable.

As a comparison point, [The Open Source Definition | Open Source Initiative](https://opensource.org/osd "The Open Source Definition | Open Source Initiative")

> 1. Free Redistribution
> 
> **The license shall not restrict any party from selling or giving away the software** as a component of an aggregate software distribution containing programs from several different sources. The license shall not require a royalty or other fee for such sale.
> 2. Source Code
> 
> The program must include source code, and **must allow distribution in source code as well as compiled form**.

This definitely disqualifies workflowengine.net as "open source". 
As far as I understand, this is a purely commercial product that ships with its (closed) source.

As a comparison, Red Hat sells service on software that is open-source: [Red Hat is Open Source; but where is the source and why can't I download RH and install it and why is there CentOS? - Quora](https://www.quora.com/Red-Hat-is-Open-Source-but-where-is-the-source-and-why-cant-I-download-RH-and-install-it-and-why-is-there-CentOS "Red Hat is Open Source; but where is the source and why can't I download RH and install it and why is there CentOS? - Quora")

Have a nice day.

**Comment by ngohungphuc** [comment]
thank @fidergo-stephane-gourichon for clarify

**Comment by thangchung** [comment]
@SebastianStehle @ngohungphuc We have already added workflow engine in our list actually. See [**Workflow**](https://github.com/thangchung/awesome-dotnet-core#workflow) section.

**Comment by fidergo-stephane-gourichon** [comment]
@SebastianStehle  Yes, if the list mixes licenses, etc, its value is highly dependent on showing badges or columns, else one has to manually check all the time or just distrust the whole list.
Example of website that shows "badges", with filtering https://alternativeto.net/software/net-core
