### ISSUE TITLE
Hello,Why is there no AOP chapter?

### ISSUE THREAD

**Issue by ByronFeng** [thangchung/awesome-dotnet-core#441]

**Comment by ByronFeng** [comment]
![image](https://user-images.githubusercontent.com/26641643/50412312-4c72d000-0841-11e9-9a1f-d89039b15841.png)

I remember earlier this location had a link to AOP

**Comment by f135ta** [comment]
Hi! I’m not really sure where to post or ask.. But I have a project for AOP that could be included on your page? Its for building AOP code on Net Core? https://github.com/f135ta/SimpleProxy - I’d love it if you included it :-)

**Comment by bjohnso5** [comment]
@f135ta I took a look at your library, and it looks like a nice wrapper around `Castle.Core`, but you should probably fill in the TODO sections in your readme before you have it added to any awesome lists.
