### ISSUE TITLE
New style to help readers identify the best libs or fw

### ISSUE THREAD

**Issue by thangchung** [thangchung/awesome-dotnet-core#442]
Today, I have an idea which helps our readers easy to identify and choose the best library or framework for them. See below

### Awesome lists
- [awesome](https://github.com/sindresorhus/awesome) - Curated list of awesome lists ![Star](https://img.shields.io/github/stars/sindresorhus/awesome.svg?style=social&label=Star) ![Fork](https://img.shields.io/github/forks/sindresorhus/awesome.svg?style=social&label=Fork)
- [awesome-nodejs](https://github.com/sindresorhus/awesome-nodejs) - Delightful Node.js packages and resources ![Star](https://img.shields.io/github/stars/sindresorhus/awesome-nodejs.svg?style=social&label=Star) ![Fork](https://img.shields.io/github/forks/sindresorhus/awesome-nodejs.svg?style=social&label=Fork)
- [awesome-dotnet-core](https://github.com/thangchung/awesome-dotnet-core) - a collection of awesome .NET core libraries, tools, frameworks and software ![Star](https://img.shields.io/github/stars/thangchung/awesome-dotnet-core.svg?style=social&label=Star) ![Fork](https://img.shields.io/github/forks/thangchung/awesome-dotnet-core.svg?style=social&label=Fork)

We add 2 more badges: `star` and `fork` to all sub-items in current list. We might write out the .NET Core program to do that, and then let the Travis CI download and compose the formats as above. Or another option is to create another `README` file, it might be `README.fancy` or something like that :p

@ngohungphuc Let me know how do you feel so that we can discuss more
@all We're willing to have your queries as well

**Comment by ngohungphuc** [comment]
I think we can do that but does it really need for the repo ?

**Comment by Jogai** [comment]
If this is used I think its way easier to use something like https://shields.io/#/examples/social

But I think the discussion should be about what the best metrics are. Do people really star/fork repos they think are awesome? In my case, the answer is no...

**Comment by LordMike** [comment]
They should be cached after the first request (on Shield.io's end) - as they use Cloudflare. It's still not awesome, but at least it doesn't hit some home-grown server setup.

Personally. This setup would annoy me a lot. I like the simplistic nature of the list, and I expect that all projects on the list are "awesome", in a sense that I don't need to evaluate if one project is "better" than another in terms of stars.

If it really must be, I would suggest a lighter layout, where (markdown permitting) the metrics are printed _after_ the description. Like this:

* [autorest](https://github.com/Azure/autorest) - Swagger (OpenAPI) Specification code generator featuring C# and Razor templates. Supports C#, Java, Node.js, TypeScript, Python and Ruby. `4.5.x or above` -- `424 forks | 2.109 stars | 964 watchers`

The new metrics should be as small and non-intruding as possible.

**Comment by Jogai** [comment]
A flatter style and a bit of coloring makes it less intrusive. Still I agree with @LordMike 

* ![autorest github/forks](https://img.shields.io/github/forks/Azure/autorest.svg?style=flat-square&colorA=A8A8A8&colorB=BBBBBB) ![autorest github/stars](https://img.shields.io/github/stars/Azure/autorest.svg?style=flat-square&colorA=A8A8A8&colorB=BBBBBB) ![autorest github/watchers](https://img.shields.io/github/watchers/Azure/autorest.svg?style=flat-square&colorA=A8A8A8&colorB=BBBBBB) [autorest](https://github.com/Azure/autorest) - Swagger (OpenAPI) Specification code generator featuring C# and Razor templates. Supports C#, Java, Node.js, TypeScript, Python and Ruby. `4.5.x or above`

**Comment by thangchung** [comment]
After a long time to investigate, I come up with not changing the current style of readme because of performance when we did a lot of requests to calculate and pull statistic. Keep it for now. Thank you all for your enthusiasm for making this repo more and more popularly.
