### ISSUE TITLE
Add Possible.Math

### ISSUE THREAD

**Issue by VictorOchoaS** [thangchung/awesome-dotnet-core#467]
Hi, could you add the project Possible.Math.Finance

https://github.com/possible-brazil/Possible.Math.Finance

**Comment by ngohungphuc** [comment]
I think this project seem quite small. I will ask @thangchung to review it, Thank you

**Comment by thangchung** [comment]
@VictorOchoaS Yeah. Two things we can clarify here. Firstly, it is too small which is can implement around 1 week with not complex logic in that. Secondly, it wasn't created too long enough (only 1 month up to now). So I will close this issue, feel free to re-open if you think we can do anything more. Thank you for your suggestion 👍

**Comment by VictorOchoaS** [comment]
@thangchung e @ngohungphuc 
Bom dia, tudo bem?
   Esse projeto é a conversão de uma classe de calculos financeiros que vem desde o excel, ela foi um grande problema em um projeto meu onde tive que realiza-lo em .net framework por não existir essa classe em .net core e a Microsoft não ter plano de converter.
   Por mais que ela seja simples, os calculos são complexos e usados em sistemas financeiros e bancarios no mundo todo. 
   Essa classe possibilita que esses sistemas sejam feitos em .Net Core.
