### ISSUE TITLE
Please add foil https://github.com/dotnetcore/surging to the list of libraries

### ISSUE THREAD

**Issue by fayuanliu** [thangchung/awesome-dotnet-core#485]
micro service :
https://github.com/dotnetcore/surging

**Comment by ngohungphuc** [comment]
I'm pretty sure that no one is understand Chinesse version. Can you translatate into English version

**Comment by mgrigore** [comment]
There is already an English version at https://github.com/dotnetcore/surging/blob/master/README.EN.md

**Comment by ngohungphuc** [comment]
Then you guys can make a PR then I will merge it.
Thank you
