### ISSUE TITLE
Roslynquoter

### ISSUE THREAD

**Issue by Diaskhan** [thangchung/awesome-dotnet-core#487]
https://roslynquoter.azurewebsites.net

Please add roslynquoter tool.

It allows from c# code generates roslyn code that creates this code.
Very usseful tool for code generation !

**Comment by Jogai** [comment]
Make a pr: https://github.com/thangchung/awesome-dotnet-core/blob/master/contributing.md

**Comment by xiaobei930** [comment]
邮件已经收到,正在处理,请等待.
