### ISSUE TITLE
Topshelf doesn't work with .net core

### ISSUE THREAD

**Issue by oliverkane** [thangchung/awesome-dotnet-core#496]
Just wanted to let you guys know that TopShelf isn't something which is supported on .NET Core. It works on linux, but you need mono.

**Comment by Jogai** [comment]
It is supporting .NET core. Could be windows only but thats because a service is a windows only thing

**Comment by thangchung** [comment]
@Jogai Yeah. Thank you @Jogai for your clarification. 
@oliverkane Feel free to open if you have any more concerns. Thank you 👍

**Comment by oliverkane** [comment]
For future googlers, this is well documented.  http://docs.topshelf-project.com/en/latest/installation/prerequisites.html

While Topshelf does say you can run your either in service mode or just simply run it from the command line, adding this library to your .net core will indeed add a hard dependency to the windows platform.

Sorry for bothering you guys!
