### ISSUE TITLE
Textual Suggestion

### ISSUE THREAD

**Issue by cognitive-arch** [thangchung/awesome-dotnet-core#508]
After spending some time on your collection I found pretty catchy slogans that you can add in your repository intro.

1. awesome-dotnet-core (Find -> Explore -> Integrate & Enjoy)

2. awesome-dotnet-core (All you need to feel better in dotnet-core )

**Comment by Jogai** [comment]
Why would an awesome list need a slogan?

**Comment by cognitive-arch** [comment]
Because awesome doesn't clear the purpose/vision of this collection. This collection is to support individuals to **find** different dotnet core libraries at one place that they can **explore** and **use/integrate**  in their solutions. Otherwise there nothing special regarding slogan.

**Comment by cognitive-arch** [comment]
I'm going to close this textual suggestion thread.  I think awesome list really don't need any slogan.
