### ISSUE TITLE
Additional CMS

### ISSUE THREAD

**Issue by CodingSamurai** [thangchung/awesome-dotnet-core#55]
Just to help out there's at least three more CMS that are working on .NET Core versions:

- Kaliko: https://github.com/KalikoCMS/KalikoCMS.Core
- Piranha:  https://github.com/PiranhaCMS/piranha.core
- Umbraco (although not for 1+ years):  http://static1.squarespace.com/static/55bf4530e4b0b2984959feba/t/5638d8d6e4b0ce96e2266472/1446566102051/RoadToV8.pdf

**Comment by thangchung** [comment]
@CodingSamurai 

> Kaliko: https://github.com/KalikoCMS/KalikoCMS.Core => **I don't see any code there using .NET Core**
Piranha: https://github.com/PiranhaCMS/piranha.core => **Please do the PR into this repo, I am happy to have it on this list. Thanks**
Umbraco (although not for 1+ years): http://static1.squarespace.com/static/55bf4530e4b0b2984959feba/t/5638d8d6e4b0ce96e2266472/1446566102051/RoadToV8.pdf => **I look at the repo at [Umbraco9](https://github.com/Shazwazza/Umbraco9), all the code are .NET Core, but also in [dev-v8](https://github.com/umbraco/Umbraco-CMS/tree/dev-v8/src/Umbraco.Core) only using .NET 4.6. So I think they will go with .NET Full framework 4.6.x**
