### ISSUE TITLE
Have you considered adding the New Bike Sharing application in the example apps

### ISSUE THREAD

**Issue by raytrask** [thangchung/awesome-dotnet-core#63]
Check out this list via.  [this google search](https://www.google.com/webhp?sourceid=chrome-instant&rlz=1C5CHFA_enUS580US580&ion=1&espv=2&ie=UTF-8#q=microsoft+bike+share+example+app).

It was introduced in the dot net connect conference in December 2016

**Comment by thangchung** [comment]
@raytrask Good point! I just have a look at the article at https://blogs.msdn.microsoft.com/visualstudio/2016/12/14/connectdemos-2016-bikesharing360-on-github/ It is really awesome. Could you do a PR into my repo into the **Articles** section? I am really appreciated about this 👍

**Comment by raytrask** [comment]
I can do that, on a crazy deadline, I'll get it in a few days.

**Comment by thangchung** [comment]
I thought the article is good because it is a collection of a lot of technics and languages, not only .NET Core. But I am fine if you think the sample projects will help another people easy to have a look at

**Comment by thangchung** [comment]
@raytrask Any progress on this? :)

**Comment by raytrask** [comment]
I’ll do it today.  Thanks for the reminder.

Thanks,
Ray Trask

We solve problems better when we speak.
So call me...
614-787-4123 (mobile)

**Comment by raytrask** [comment]
Done.  I split them into to pull requests to give you more flexibility.

**Comment by thangchung** [comment]
@raytrask Okay, Thank Ray so much. I close this issue now.
