### ISSUE TITLE
Add AutoComplete to Searching 

### ISSUE THREAD

**Issue by omerfarukz** [thangchung/awesome-dotnet-core#65]
Can you please add autocomplete library to Serching section?

https://github.com/omerfarukz/autocomplete

**Comment by thangchung** [comment]
@omerfarukz Thanks for your report, but could you do a PR into my repo so that I can add it :)

**Comment by omerfarukz** [comment]
It is done.

**Comment by thangchung** [comment]
I can't see any Pull Request from you :(

**Comment by omerfarukz** [comment]
So sorry, now you can see :)

**Comment by thangchung** [comment]
@omerfarukz Okay. I close this issue for now.
