### ISSUE TITLE
Add [Book] Entity Framework Core in Action

### ISSUE THREAD

**Issue by Chibuikekenneth** [thangchung/awesome-dotnet-core#667]
Could You add this [Book ](https://www.amazon.com/Entity-Framework-Core-Action-Smith/dp/161729456X) among the BOOKS sections  ??

> This is a really nice Book especially for those who really wants to understand Entity Framework Core. Especially when working on Projects using Asp.Net Core. Also has a lot of Good Reviews on Amazon.

https://www.amazon.com/Entity-Framework-Core-Action-Smith/dp/161729456X

**Comment by ngohungphuc** [comment]
You can create a PR then we will merge it for you. 
Thank you
