### ISSUE TITLE
Add Anno.Core

### ISSUE THREAD

**Issue by duyanming** [thangchung/awesome-dotnet-core#763]
1. Have your repository in Github or any source control been created at least 3 months? 

>Yes,  The project was started in 2016 and opened source in 2020

   https://github.com/duyanming/Anno.Core
  Dashboard ([https://github.com/duyanming/Viper](https://github.com/duyanming/Viper))
2. The reason you think your library/framework/tooling/link is awesome?
    
Anno is a rapid development framework for microservices, and the underlying communication can switch between GRPC and Thrift at will.With its own service discovery, call chain tracking, statistical analysis, monitoring, Dashboard ([Viper](https://github.com/duyanming/Viper)), Cron scheduling, flow limiting, event bus, CQRS, DDD, plug-in development
![Dashboard](https://img2020.cnblogs.com/blog/998152/202105/998152-20210513180725509-1879824767.png)
![Dashboard](https://z3.ax1x.com/2021/04/01/cE58JO.png)
![Dashboard](https://img2020.cnblogs.com/blog/998152/202105/998152-20210513180900407-75070503.png)

3. Have your PR follows up with alphabet-ordering?

https://github.com/duyanming/Anno.Core
https://github.com/duyanming/Viper

4. Is it .NET Core or .NET Standard?
.NET Core 、 .NET Standard、FrameWork、[Java](https://github.com/duyanming/anno.thrift-parent)

5. Have you read through the README or issues list to make sure that your PR is not duplicated to any others?
Yes

**Comment by Jogai** [comment]
Looks awesome, but is there english documentation?
