### ISSUE TITLE
Add Squidex

### ISSUE THREAD

**Issue by SebastianStehle** [thangchung/awesome-dotnet-core#84]
Hi,

we are working on a headless CMS for ASP.NET Core. Would be really awesome if you add it: https://github.com/Squidex/squidex

Best regards,
Sebastian

**Comment by thangchung** [comment]
@SebastianStehle Just have a look at it. The code is really fantastic. One question, I have seen that there is the headless CMS like https://graphcms.com. Is that the same ideas with you?

**Comment by SebastianStehle** [comment]
@thangchung The idea is the same and the concept of a headless CMS is a not invented by us.

Thank you very much.

There are also similar products, e.g.

* https://github.com/directus/directus
* https://www.contentful.com/

The big difference (besides that squidex is Open Source and ASP.NET Core) is that we think that any non-trivial application will always use different data technologies, e.g. sql server + mongodb + elastic search + redis + Neo4j. Therefore we use event sourcing for squidex and we also plan to build integration points to rabbitmq, kafka and webhooks to make it easy to create copies of your data. But we are at the very beginning and there is so much to do.

**Comment by thangchung** [comment]
@SebastianStehle Thanks for many sharing from you. Could you please do that Pull Request so that you can participate in this project as well
