### ISSUE TITLE
Simple and good tutorial about how to add authorization

### ISSUE THREAD

**Issue by hong-duc** [thangchung/awesome-dotnet-core#95]
I found this when I try to learn how to add authorization in project, it very simple and not use Identity Framework
https://github.com/blowdart/AspNetAuthorizationWorkshop

I could make a PR but I don't know what category to put in

**Comment by thangchung** [comment]
@hong-duc Thanks for your suggestion. I just have a look at that project, really cool. Please make a PR and put it into the **Sample Projects** section by the alphabet order.

**Comment by thangchung** [comment]
Any progress on this one?

**Comment by hong-duc** [comment]
:smile:  sorry for late reply , was busy study for test last week, I will make a PR tonight

**Comment by hong-duc** [comment]
I have create PR #97
