### ISSUE TITLE
Add Avalonia

### ISSUE THREAD

**Issue by Mixaill** [thangchung/awesome-dotnet-core#96]
GUI Framework

https://github.com/AvaloniaUI/Avalonia
https://github.com/AvaloniaUI/avalonia-dotnet-templates

**Comment by thangchung** [comment]
@Mixaill I just have a look at the Avalonia UI framework. Really cool. Could you please make a PR into this repo (section [**Application Frameworks**](https://github.com/thangchung/awesome-dotnet-core#application-frameworks) is the best fix for it)?
